theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true
  tables: true
  hard_wrap: false
  math_engine_opts:
    preview: true
    preview_as_code: false

# MathJax configuration
mathjax:
  source: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  config: |
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        displayMath: [['$$', '$$'], ['\\[', '\\]']],
        processEscapes: true,
        processEnvironments: true
      },
      options: {
        skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre']
      }
    };

# GitHub Pages settings
title: "Appunti Calcolatori Elettronici 2024-2025"
description: "Appunti del corso di Calcolatori Elettronici - Università di Pisa"
baseurl: ""
url: ""

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - .gitignore
  - LICENSE