theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true
  tables: true
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: true
      wrap: true

# GitHub Pages settings
title: "Appunti Calcolatori Elettronici 2024-2025"
description: "Appunti del corso di Calcolatori Elettronici - Università di Pisa"
baseurl: ""
url: ""

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - .gitignore
  - LICENSE